SELECT B.CATEGORY as CATEGORY, SUM(S.SALES) as TOTAL_SALES
FROM BOOK B JOIN BOOK_SALES S on B.BOOK_ID = S.BOOK_ID
WHERE DATE_FORMAT(S.SALES_DATE, '%Y') = 2022 and DATE_FORMAT(S.SALES_DATE, '%m') = 01
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY ASC;
